In [13]:
import numpy as np
from imutils import paths
import cv2
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import classification_report,accuracy_score
import pandas as pd 
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow import keras
from PIL import Image

In [30]:
path = ('C:/Users/borak/AMLS/dataset/image')

img_paths = sorted(list(paths.list_images(path)))

img_list = []

for path in img_paths:
    image_file = cv2.imread(path)
    resized = cv2.resize(image_file,(64,64))
    gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)
    img_list.append(gray)

In [31]:
X = []
Y = []

labeldata = pd.read_csv ('C:/Users/borak/AMLS/dataset/label.csv')

for i in range (0,3000):
    X.append(img_list[i])
    if ("no_tumor") in (labeldata.iat[i,1]):
        Y.append(0)
    elif ("meningioma_tumor") in (labeldata.iat[i,1]):
        Y.append(1)
    elif ("glioma_tumor") in (labeldata.iat[i,1]):
        Y.append(2)
    elif ("pituitary_tumor") in (labeldata.iat[i,1]):
        Y.append(3)

In [32]:
Y=np.array(Y)
Y=Y.flatten()
#Y

In [33]:
X=np.array(X) 
X_resized=X.reshape(-1,64,64,1) 
X_resized=X_resized/255.0
#X_resized

In [34]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from numpy import array
from numpy import argmax

In [35]:
values = array(Y)
encoder = LabelEncoder()
integer_encoded = encoder.fit_transform(values)
#print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Activation
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout

In [45]:
model=Sequential()
model.add(Convolution2D(64,(5,5),input_shape=X_resized.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

#model.add(Dropout(0.2))

model.add(Convolution2D(64,(3,3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(128))
model.add(Activation("relu"))
model.add(Dropout(0.2))
model.add(Dense(4))
model.add(Activation('softmax'))

model.compile(loss="categorical_crossentropy",
             optimizer="adam",
             metrics=['accuracy'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_14 (Conv2D)          (None, 60, 60, 64)        1664      
                                                                 
 activation_32 (Activation)  (None, 60, 60, 64)        0         
                                                                 
 max_pooling2d_14 (MaxPoolin  (None, 30, 30, 64)       0         
 g2D)                                                            
                                                                 
 conv2d_15 (Conv2D)          (None, 28, 28, 64)        36928     
                                                                 
 activation_33 (Activation)  (None, 28, 28, 64)        0         
                                                                 
 max_pooling2d_15 (MaxPoolin  (None, 14, 14, 64)       0         
 g2D)                                                 

In [46]:
model.fit(X_resized,onehot_encoded,batch_size=32,epochs=12,validation_split=0.15)

Epoch 1/12
80/80 [==============================] - 6s 69ms/step - loss: 1.0276 - accuracy: 0.5608 - val_loss: 0.8667 - val_accuracy: 0.6200
Epoch 2/12
80/80 [==============================] - 6s 70ms/step - loss: 0.6903 - accuracy: 0.7220 - val_loss: 0.6413 - val_accuracy: 0.7511
Epoch 3/12
80/80 [==============================] - 6s 72ms/step - loss: 0.5394 - accuracy: 0.7906 - val_loss: 0.5827 - val_accuracy: 0.7844
Epoch 4/12
80/80 [==============================] - 6s 70ms/step - loss: 0.4426 - accuracy: 0.8267 - val_loss: 0.5373 - val_accuracy: 0.7867
Epoch 5/12
80/80 [==============================] - 6s 72ms/step - loss: 0.3007 - accuracy: 0.8941 - val_loss: 0.4995 - val_accuracy: 0.7956
Epoch 6/12
80/80 [==============================] - 6s 71ms/step - loss: 0.2140 - accuracy: 0.9239 - val_loss: 0.4141 - val_accuracy: 0.8622
Epoch 7/12
80/80 [==============================] - 6s 70ms/step - loss: 0.1573 - accuracy: 0.9459 - val_loss: 0.4900 - val_accuracy: 0.8200
Epoch 8/12
80

In [47]:
plot(Epoch,loss)

NameError: name 'plot' is not defined